/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return {
      beforeFiles: [
        { source: '/', destination: '/index.html' },
        { source: '/about-us', destination: '/about.html' },
        { source: '/contact', destination: '/contact.html' },
        { source: '/locations', destination: '/locations.html' },
        { source: '/plumbing', destination: '/plumbing.html' },
        { source: '/hvac', destination: '/hvac.html' },
        { source: '/anthem-branded-location-lp', destination: '/Anthem Branded Location LP.html' },
        { source: '/privacy-policy', destination: '/privacy-policy.html' },
        { source: '/terms-of-service', destination: '/terms-of-service.html' },
        { source: '/palm-springs', destination: '/longmont.html' },
        { source: '/palm-desert', destination: '/anthem-palm-desert.html' },
        { source: '/indio', destination: '/thornton.html' },
        { source: '/cathedral-city', destination: '/broomfield.html' },
        { source: '/la-quinta', destination: '/lafayette.html' },
        { source: '/coachella', destination: '/arvada.html' },
        { source: '/desert-hot-springs', destination: '/lakewood.html' },
        { source: '/rancho-mirage', destination: '/commerce-city.html' },
        { source: '/coachella-valley', destination: '/anthem-ac-plumbing.html' },
        { source: '/anthem', destination: '/boulder.html' },
        { source: '/phoenix', destination: '/longmont.html' },
        { source: '/glendale', destination: '/broomfield.html' },
        { source: '/peoria', destination: '/thornton.html' },
        { source: '/scottsdale', destination: '/commerce-city.html' },
        { source: '/cave-creek', destination: '/lakewood.html' },
        { source: '/new-river', destination: '/arvada.html' },
        { source: '/deer-valley', destination: '/lafayette.html' },
        { source: '/boulder', destination: '/boulder.html' },
        { source: '/longmont', destination: '/longmont.html' },
        { source: '/broomfield', destination: '/broomfield.html' },
        { source: '/thornton', destination: '/thornton.html' },
        { source: '/commerce-city', destination: '/commerce-city.html' },
        { source: '/lakewood', destination: '/lakewood.html' },
        { source: '/arvada', destination: '/arvada.html' },
        { source: '/lafayette', destination: '/lafayette.html' },
        { source: '/boiler-repair-boulder-co', destination: '/boiler-repair-boulder-co.html' },
      ],
    };
  },
  async redirects() {
    return [
      { source: '/about', destination: '/about-us', permanent: true },
      { source: '/about.html', destination: '/about-us', permanent: true },
      { source: '/aboutus', destination: '/about-us', permanent: true },
      { source: '/contact.html', destination: '/contact', permanent: true },
      { source: '/locations.html', destination: '/locations', permanent: true },
      { source: '/plumbing.html', destination: '/plumbing', permanent: true },
      { source: '/hvac.html', destination: '/hvac', permanent: true },
      { source: '/privacy-policy.html', destination: '/privacy-policy', permanent: true },
      { source: '/terms-of-service.html', destination: '/terms-of-service', permanent: true },
      { source: '/longmont.html', destination: '/palm-springs', permanent: true },
      { source: '/anthem-palm-desert.html', destination: '/palm-desert', permanent: true },
      { source: '/thornton.html', destination: '/indio', permanent: true },
      { source: '/broomfield.html', destination: '/cathedral-city', permanent: true },
      { source: '/lafayette.html', destination: '/la-quinta', permanent: true },
      { source: '/arvada.html', destination: '/coachella', permanent: true },
      { source: '/lakewood.html', destination: '/desert-hot-springs', permanent: true },
      { source: '/commerce-city.html', destination: '/rancho-mirage', permanent: true },
      { source: '/anthem-ac-plumbing.html', destination: '/coachella-valley', permanent: true },
      { source: '/sewer-line-repair-and-replacement.html', destination: '/services/sewer-line-repair-and-replacement', permanent: true },
      { source: '/water-heater-repair-and-replacement.html', destination: '/services/water-heater-repair-and-replacement', permanent: true },
      { source: '/hydro-jetting.html', destination: '/services/hydro-jetting', permanent: true },
      { source: '/water-heaters.html', destination: '/services/water-heaters', permanent: true },
      { source: '/ac.html', destination: '/services/cooling', permanent: true },
      { source: '/heater.html', destination: '/services/heating', permanent: true },
      { source: '/drain-cleaning', destination: '/services/drain-cleaning', permanent: true },
      { source: '/water-heaters', destination: '/services/water-heaters', permanent: true },
      { source: '/ac-repair', destination: '/services/ac-repair', permanent: true },
    ];
  },
};

module.exports = nextConfig;
