/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      { source: '/index.html', destination: '/', permanent: true },
      { source: '/about', destination: '/about-us', permanent: true },
      { source: '/about.html', destination: '/about-us', permanent: true },
      { source: '/aboutus', destination: '/about-us', permanent: true },
      { source: '/contact.html', destination: '/contact', permanent: true },
      { source: '/locations.html', destination: '/locations', permanent: true },
      { source: '/plumbing.html', destination: '/plumbing', permanent: true },
      { source: '/hvac.html', destination: '/hvac', permanent: true },
      { source: '/privacy-policy.html', destination: '/privacy-policy', permanent: true },
      { source: '/terms-of-service.html', destination: '/terms-of-service', permanent: true },
      { source: '/services.html', destination: '/services', permanent: true },
      { source: '/longmont.html', destination: '/palm-springs', permanent: true },
      { source: '/anthem-palm-desert.html', destination: '/palm-desert', permanent: true },
      { source: '/thornton.html', destination: '/indio', permanent: true },
      { source: '/broomfield.html', destination: '/cathedral-city', permanent: true },
      { source: '/lafayette.html', destination: '/la-quinta', permanent: true },
      { source: '/arvada.html', destination: '/coachella', permanent: true },
      { source: '/lakewood.html', destination: '/desert-hot-springs', permanent: true },
      { source: '/commerce-city.html', destination: '/rancho-mirage', permanent: true },
      { source: '/anthem-ac-plumbing.html', destination: '/coachella-valley', permanent: true },
      { source: '/sewer-line-repair-and-replacement.html', destination: '/services/sewer-line-repair-and-replacement', permanent: true },
      { source: '/water-heater-repair-and-replacement.html', destination: '/services/water-heater-repair-and-replacement', permanent: true },
      { source: '/hydro-jetting.html', destination: '/services/hydro-jetting', permanent: true },
      { source: '/water-heaters.html', destination: '/services/water-heaters', permanent: true },
      { source: '/ac.html', destination: '/services/cooling', permanent: true },
      { source: '/heater.html', destination: '/services/heating', permanent: true },
      { source: '/drain-cleaning', destination: '/services/drain-cleaning', permanent: true },
      { source: '/water-heaters', destination: '/services/water-heaters', permanent: true },
      { source: '/ac-repair', destination: '/services/ac-repair', permanent: true },
      { source: '/anthem', destination: '/palm-springs', permanent: true },
      { source: '/boulder', destination: '/palm-springs', permanent: true },
      { source: '/longmont', destination: '/palm-springs', permanent: true },
      { source: '/broomfield', destination: '/cathedral-city', permanent: true },
      { source: '/thornton', destination: '/indio', permanent: true },
      { source: '/commerce-city', destination: '/rancho-mirage', permanent: true },
      { source: '/lakewood', destination: '/desert-hot-springs', permanent: true },
      { source: '/arvada', destination: '/coachella', permanent: true },
      { source: '/lafayette', destination: '/la-quinta', permanent: true },
      { source: '/phoenix', destination: '/palm-springs', permanent: true },
      { source: '/glendale', destination: '/cathedral-city', permanent: true },
      { source: '/peoria', destination: '/indio', permanent: true },
      { source: '/scottsdale', destination: '/rancho-mirage', permanent: true },
      { source: '/cave-creek', destination: '/desert-hot-springs', permanent: true },
      { source: '/new-river', destination: '/coachella', permanent: true },
      { source: '/deer-valley', destination: '/la-quinta', permanent: true },
    ];
  },
};

module.exports = nextConfig;
